#ifndef GW_SETTINGSWINDOW_PRIVATE_INCLUDED
#define GW_SETTINGSWINDOW_PRIVATE_INCLUDED

G_BEGIN_DECLS

typedef enum {
  GW_SETTINGSWINDOW_SIGNALID_ROMAJI_KANA,
  GW_SETTINGSWINDOW_SIGNALID_HIRA_KATA,
  GW_SETTINGSWINDOW_SIGNALID_KATA_HIRA,
  GW_SETTINGSWINDOW_SIGNALID_USE_GLOBAL_DOCUMENT_FONT,
  GW_SETTINGSWINDOW_SIGNALID_GLOBAL_DOCUMENT_FONT,
  GW_SETTINGSWINDOW_SIGNALID_CUSTOM_FONT,
  GW_SETTINGSWINDOW_SIGNALID_SEARCH_AS_YOU_TYPE,
  GW_SETTINGSWINDOW_SIGNALID_SPELLCHECK,
  GW_SETTINGSWINDOW_SIGNALID_MATCH_FG,
  GW_SETTINGSWINDOW_SIGNALID_MATCH_BG,
  GW_SETTINGSWINDOW_SIGNALID_COMMENT_FG,
  GW_SETTINGSWINDOW_SIGNALID_COMMENT_BG,
  GW_SETTINGSWINDOW_SIGNALID_HEADER_FG,
  GW_SETTINGSWINDOW_SIGNALID_HEADER_BG,
  TOTAL_GW_SETTINGSWINDOW_SIGNALIDS
} GwSettingsWindowSignalIds;

struct _GwSettingsWindowPrivate {
  GtkNotebook *notebook;
  guint signalids[TOTAL_GW_SETTINGSWINDOW_SIGNALIDS];
//  guint timeoutids[TOTAL_GW_SETTINGSWINDOW_TIMEOUTIDS];
};

#define GW_SETTINGSWINDOW_GET_PRIVATE(object)(G_TYPE_INSTANCE_GET_PRIVATE ((object), GW_TYPE_SETTINGSWINDOW, GwSettingsWindowPrivate))

G_END_DECLS

#endif

