#ifndef GW_TEXTTAGTABLE_PRIVATE_INCLUDED
#define GW_TEXTTAGTABLE_PRIVATE_INCLUDED

G_BEGIN_DECLS

typedef enum { 
  GW_TEXTTAGTABLE_SIGNALID_MATCH_FG,
  GW_TEXTTAGTABLE_SIGNALID_MATCH_BG,
  GW_TEXTTAGTABLE_SIGNALID_HEADER_FG,
  GW_TEXTTAGTABLE_SIGNALID_HEADER_BG,
  GW_TEXTTAGTABLE_SIGNALID_COMMENT_FG,
  TOTAL_GW_TEXTTAGTABLE_SIGNALIDS
} GwTextTagTableColumn;

struct _GwTextTagTablePrivate {
  GwApplication *application;
  guint signalid[TOTAL_GW_TEXTTAGTABLE_SIGNALIDS];
};

#define GW_TEXTTAGTABLE_GET_PRIVATE(object)(G_TYPE_INSTANCE_GET_PRIVATE ((object), GW_TYPE_TEXTTAGTABLE, GwTextTagTablePrivate))

G_END_DECLS

#endif

